# fly.toml app configuration file generated for rubberduckie-bot on 2025-02-04T14:55:24Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rubberduckie-bot'
primary_region = 'lax'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
max_machines_running = 1
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
memory_mb = 1024
